# Site settings
title: nicholas becker
email: nbecker6 - at - jhu - dot - edu
emailLink: nbecker6@jhu.edu
description: > # this means to ignore newlines until "baseurl:"
  department of cognitive science, <br>
  johns hopkins university
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://callmenick.net" # the base hostname & protocol for your site
#github_username:  nrbecker

#CNAME (http://callmenick.com)

# Build settings
markdown: kramdown

kramdown:
 input: GFM